workflows:
  ios-build:
    name: NotatkiApp iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Resolve dependencies
        script: |
          cd NotatkiApp
          swift package resolve

      - name: Build iOS IPA (unsigned)
        script: |
          cd NotatkiApp
          xcodebuild \
            -scheme "NotatkiApp" \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath ../DerivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=NO \
            -destination "generic/platform=iOS" \
            clean build

          cd ..
          mkdir -p Payload
          cp -r DerivedData/Build/Products/Release-iphoneos/NotatkiApp.app Payload/
          zip -r NotatkiApp.ipa Payload/

    artifacts:
      - "*.ipa"
    publishing:
      email:
        recipients:
          - franlo.wojtera@outlook.com
        notify:
          success: true
          failure: true
